name: Weater Repoter

on: 
  push:
  schedule:
    - cron: '0 23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: 'Get Weather'
      run: bash ./weather.sh
    - name: 'Get Date'
      run: echo "::set-env name=REPORT_DATE::$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')"
    - name: 'Send mail'
      uses: dawidd6/action-send-mail@master
      with:
        server_address: smtp.163.com
        server_port: 465
        username: ${{secrets.MAIL_163_USERNAME}}
        password: ${{secrets.MAIL_163_PASSWORD}}
        subject: Zhengzhou Weather Report (${{env.REPORT_DATE}})
        # Literal body:
        # body: Build job of ${{github.repository}} completed successfully!
        # Read file contents as body:
        body: file://result.html
        to: zhonghua00700@qq.com
        from: Lord
        # Optional content type:
        content_type: text/html

    - name: Run a multi-line script
      run:
        echo Add other actions to build,
        echo test, and deploy your project.
